// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SystemInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfoRequest) Reset()         { *m = SystemInfoRequest{} }
func (m *SystemInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SystemInfoRequest) ProtoMessage()    {}
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *SystemInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfoRequest.Unmarshal(m, b)
}
func (m *SystemInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfoRequest.Marshal(b, m, deterministic)
}
func (m *SystemInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfoRequest.Merge(m, src)
}
func (m *SystemInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SystemInfoRequest.Size(m)
}
func (m *SystemInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfoRequest proto.InternalMessageInfo

type SystemInfoReply struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Heigth               uint64   `protobuf:"varint,3,opt,name=heigth,proto3" json:"heigth,omitempty"`
	OS                   string   `protobuf:"bytes,4,opt,name=OS,proto3" json:"OS,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Clock                string   `protobuf:"bytes,6,opt,name=clock,proto3" json:"clock,omitempty"`
	Broadhash            string   `protobuf:"bytes,7,opt,name=broadhash,proto3" json:"broadhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfoReply) Reset()         { *m = SystemInfoReply{} }
func (m *SystemInfoReply) String() string { return proto.CompactTextString(m) }
func (*SystemInfoReply) ProtoMessage()    {}
func (*SystemInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *SystemInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfoReply.Unmarshal(m, b)
}
func (m *SystemInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfoReply.Marshal(b, m, deterministic)
}
func (m *SystemInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfoReply.Merge(m, src)
}
func (m *SystemInfoReply) XXX_Size() int {
	return xxx_messageInfo_SystemInfoReply.Size(m)
}
func (m *SystemInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfoReply proto.InternalMessageInfo

func (m *SystemInfoReply) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *SystemInfoReply) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SystemInfoReply) GetHeigth() uint64 {
	if m != nil {
		return m.Heigth
	}
	return 0
}

func (m *SystemInfoReply) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *SystemInfoReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SystemInfoReply) GetClock() string {
	if m != nil {
		return m.Clock
	}
	return ""
}

func (m *SystemInfoReply) GetBroadhash() string {
	if m != nil {
		return m.Broadhash
	}
	return ""
}

func init() {
	proto.RegisterType((*SystemInfoRequest)(nil), "rpc.SystemInfoRequest")
	proto.RegisterType((*SystemInfoReply)(nil), "rpc.SystemInfoReply")
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47) }

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xcd, 0x6e, 0xdb, 0x65, 0x07, 0xff, 0xe0, 0xb8, 0xac, 0x51, 0x3c, 0x94, 0x9e, 0x7a,
	0xca, 0x41, 0xc1, 0xab, 0xd0, 0x8b, 0xf4, 0x20, 0x5b, 0xda, 0x4f, 0xd0, 0xc6, 0xb8, 0x29, 0xd6,
	0x26, 0x26, 0x51, 0xe8, 0x67, 0xf2, 0x4b, 0x4a, 0x53, 0xa5, 0x0b, 0x7b, 0x9b, 0xf7, 0x7b, 0x3c,
	0x66, 0xe6, 0xc1, 0xa9, 0x1d, 0xac, 0x13, 0x1f, 0x4c, 0x1b, 0xe5, 0x14, 0x2e, 0x8d, 0xe6, 0xc9,
	0x15, 0x5c, 0x56, 0x1e, 0xe6, 0xfd, 0x9b, 0x2a, 0xc5, 0xe7, 0x97, 0xb0, 0x2e, 0xf9, 0x21, 0x70,
	0x71, 0x48, 0x75, 0x37, 0xe0, 0x39, 0x2c, 0xf2, 0x82, 0x92, 0x98, 0xa4, 0xeb, 0x72, 0x91, 0x17,
	0x88, 0x10, 0x68, 0x65, 0x1c, 0x5d, 0xc4, 0x24, 0x0d, 0x4b, 0x3f, 0xe3, 0x16, 0x22, 0x29, 0xda,
	0xbd, 0x93, 0x74, 0x19, 0x93, 0x34, 0x28, 0xff, 0xd4, 0x98, 0xdd, 0x55, 0x34, 0x98, 0xb2, 0xbb,
	0x0a, 0x29, 0xac, 0xbe, 0x85, 0xb1, 0xad, 0xea, 0x69, 0xe8, 0xe1, 0xbf, 0xc4, 0x0d, 0x84, 0xbc,
	0x53, 0xfc, 0x9d, 0x46, 0x9e, 0x4f, 0x02, 0xef, 0x60, 0xdd, 0x18, 0x55, 0xbf, 0xca, 0xda, 0x4a,
	0xba, 0xf2, 0xce, 0x0c, 0xee, 0x5f, 0x00, 0xe6, 0x63, 0xf1, 0x09, 0xce, 0x9e, 0x85, 0x3b, 0x00,
	0x5b, 0x66, 0x34, 0x67, 0x47, 0x4f, 0xde, 0x6e, 0x8e, 0xb8, 0xee, 0x86, 0xe4, 0x24, 0x7b, 0x84,
	0x9b, 0x56, 0xb1, 0xfd, 0x68, 0x36, 0xe3, 0x76, 0x2e, 0xeb, 0xb6, 0x67, 0x53, 0x73, 0xd9, 0x75,
	0x36, 0xa3, 0x29, 0xca, 0x8a, 0xb1, 0xcc, 0x82, 0x34, 0x91, 0x6f, 0xf5, 0xe1, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x68, 0x75, 0x02, 0x65, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemInfoClient is the client API for SystemInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemInfoClient interface {
	GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoReply, error)
}

type systemInfoClient struct {
	cc *grpc.ClientConn
}

func NewSystemInfoClient(cc *grpc.ClientConn) SystemInfoClient {
	return &systemInfoClient{cc}
}

func (c *systemInfoClient) GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoReply, error) {
	out := new(SystemInfoReply)
	err := c.cc.Invoke(ctx, "/rpc.SystemInfo/GetSystemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemInfoServer is the server API for SystemInfo service.
type SystemInfoServer interface {
	GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoReply, error)
}

// UnimplementedSystemInfoServer can be embedded to have forward compatible implementations.
type UnimplementedSystemInfoServer struct {
}

func (*UnimplementedSystemInfoServer) GetSystemInfo(ctx context.Context, req *SystemInfoRequest) (*SystemInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}

func RegisterSystemInfoServer(s *grpc.Server, srv SystemInfoServer) {
	s.RegisterService(&_SystemInfo_serviceDesc, srv)
}

func _SystemInfo_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInfoServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SystemInfo/GetSystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInfoServer).GetSystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.SystemInfo",
	HandlerType: (*SystemInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _SystemInfo_GetSystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
