version: "2"
services:

  blockchain:
    image: blockchain-testnet
    container_name: testnet-3
    volumes:
      - ../../:/go/src/bitbucket.org/axelsheva/blockchain
    networks:
      blockchain-testnet:
        ipv4_address: 11.0.3.1
    env_file:
      - .env
    restart: always

networks:
  blockchain-testnet:
    external:
      name: blockchain-testnet
